emails_autorizados:
- fcltenciano@gmail.com
- francistenciano@gmail.com
- renatinhobsb@gmail.com
- adriano.kor@gmail.com
- alvaro.kaires@gmail.com
- essiflores@gmail.com
- vitorhtcassanelli@gmail.com
- wogit33@gmail.com
- gabrielgorensteinbrasil@gmail.com
- luisalbertolalf@gmail.com
- e.somenzari@gmail.com
- csilvalmeida@gmail.com
- claurocar@gmail.com
- jairfalk5@gmail.com
- eeldercaetano@gmail.com
- leandroschwantz08@gmail.com
- leobm1982@gmail.com
- pr.evertonthiago@gmail.com
- eluanairma@gmail.com
- liviabentzem@gmail.com
- chicoso2020@gmail.com
- flaviobarros.trader@gmail.com
- tiagofagundestrader@gmail.com
- eng.fabiobarbosa@gmail.com
- carloshachtrader@gmail.com
- miyoshialexsandra@gmail.com
- olga.vivianevi@gmail.com
- raynes.caetano@gmail.com
- weverttreis@gmail.com
- josimax@gmail.com
- lisboatrader01@gmail.com
- elder.albertino@gmail.com
- alanziw@gmail.com
- fredericmacedo17@gmail.com
- mauriciopolli@gmail.com
- dsaredes@gmail.com
